# Generate AI-assisted Braille feedback with a rule-based fallback.
import json
import os

from anthropic import Anthropic

client = Anthropic(
    api_key=os.getenv("ANTHROPIC_API_KEY")
)


#def generate_rule_based_explanation(target_letter, expected, actual, result, wrong_letters=None):
def generate_rule_based_explanation(
    target_letter,
    expected,
    actual,
    result,
    wrong_letters=None,
):
    is_correct = result.get("isCorrect", False)
    error_type = result.get("errorType", "")
    diff = result.get("diff", {})

    missing_dots = diff.get("missingDots", [])
    extra_dots = diff.get("extraDots", [])

    is_frequent_mistake = False

    if target_letter and wrong_letters:
        if target_letter in wrong_letters:
            is_frequent_mistake = True

    if is_correct:
        return {
            "source": "rule-based",
            "explanation": f"Correct. The letter '{target_letter}' uses dots {expected}.",
            "learningTip": "Try to remember this pattern visually and physically.",
            "nextStep": "Continue practicing with a new letter."
        }

    if error_type == "missing_dot":
        message = f"You missed dot(s): {missing_dots}."
        if is_frequent_mistake:
            message += " This is a letter you often find difficult."

        return {
            "source": "rule-based",
            "explanation": message,
            "learningTip": "Compare your selected dots with the correct Braille pattern.",
            "nextStep": "Try this letter again and focus on the missing dots."
        }

    if error_type == "extra_dot":
        return {
            "source": "rule-based",
            "explanation": f"You selected extra dot(s): {extra_dots}. These dots should not be included.",
            "learningTip": "Focus on selecting only the dots required for the target letter.",
            "nextStep": "Remove the extra dots and try again."
        }

    if error_type == "incorrect_combination":
        return {
            "source": "rule-based",
            "explanation": f"Your answer has missing dot(s): {missing_dots} and extra dot(s): {extra_dots}.",
            "learningTip": "Check each dot position carefully before submitting.",
            "nextStep": "Practice this letter again step by step."
        }

    return {
        "source": "rule-based",
        "explanation": "The answer is not correct, but the system could not identify a specific error type.",
        "learningTip": "Review the correct Braille pattern and try again.",
        "nextStep": "Repeat this practice item."
    }


def generate_ai_prompt(target_letter, expected, actual, result, wrong_letters=None):
    return f"""
You are a Braille learning assistant.

Please generate simple feedback for a beginner learner.

Target letter: {target_letter}
Correct Braille dots: {expected}
Student selected dots: {actual}
Evaluation result: {result}
Frequently incorrect letters for this student: {wrong_letters}

Please return ONLY valid JSON.

Format:
{{
  "explanation": "...",
  "learningTip": "...",
  "nextStep": "..."
}}

Do not include markdown.
Do not include headings.
Do not include bullet points.
Return JSON only.

Use simple English.
Do not be too long.
"""


def generate_real_ai_explanation(
    target_letter,
    expected,
    actual,
    result,
    wrong_letters=None,
):
    """Generate feedback using the configured Claude model."""
    print("Trying real AI feedback.")

    api_key = os.getenv("ANTHROPIC_API_KEY")
    print("API key exists:", bool(api_key))

    if not api_key:
        return None

    prompt = generate_ai_prompt(
        target_letter,
        expected,
        actual,
        result,
        wrong_letters
    )

    try:
        print("Sending request to Claude.")

        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=200,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        print("AI response received.")

        ai_text = response.content[0].text.strip()
        
        # Remove Markdown code fences if the response contains them.
        if ai_text.startswith("```"):
            ai_text = ai_text.replace("```json", "")
            ai_text = ai_text.replace("```", "")
            ai_text = ai_text.strip()
        try:
            ai_data = json.loads(ai_text)
        except Exception as e:
            print("JSON parse error:", e)
            print("Raw AI text:", ai_text)

            return {
                "source": "real-ai",
                "explanation": ai_text,
                "learningTip": "Generated by Claude AI.",
                "nextStep": "Continue practicing."
            }

        return {
            "source": "real-ai",
            "explanation": ai_data.get("explanation", ""),
            "learningTip": ai_data.get("learningTip", ""),
            "nextStep": ai_data.get("nextStep", "")
        }

    except Exception as e:
        print("AI API error:", e)
        return None

def generate_ai_explanation(target_letter, expected, actual, result, wrong_letters=None):
    """
    Generate AI feedback and use rule-based feedback when AI is unavailable.
    """

    real_ai_result = generate_real_ai_explanation(
        target_letter,
        expected,
        actual,
        result,
        wrong_letters
    )

    if real_ai_result:
        return real_ai_result

    return generate_rule_based_explanation(
        target_letter,
        expected,
        actual,
        result,
        wrong_letters
    )